
version: "3"

networks:
  my-network:
    external: true

services:
  blog:
    container_name: blog
    build:
      context: ./blog
      dockerfile: Dockerfile
    ports:
      - 3000:80
    networks:
      - my-network


  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-network



